// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TaskManager.Data;

#nullable disable

namespace TaskManager.Data.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250325000000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("TaskManager.Models.TaskItem", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<int>("Complexity")
                .HasColumnType("integer")
                .HasColumnName("complexity");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            b.Property<string>("DeviceId")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("device_id");

            b.Property<string>("DueDate")
                .HasMaxLength(10)
                .HasColumnType("character varying(10)")
                .HasColumnName("due_date");

            b.Property<int>("Importance")
                .HasColumnType("integer")
                .HasColumnName("importance");

            b.Property<bool>("IsComplete")
                .HasColumnType("boolean")
                .HasColumnName("is_complete");

            b.Property<Guid>("ListId")
                .HasColumnType("uuid")
                .HasColumnName("list_id");

            b.Property<int>("Priority")
                .HasColumnType("integer")
                .HasColumnName("priority");

            b.Property<string>("Tag")
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("tag");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("title");

            b.HasKey("Id");

            b.HasIndex("DeviceId");

            b.HasIndex("ListId");

            b.ToTable("tasks", (string)null);

            b.HasOne("TaskManager.Models.TodoList", null)
                .WithMany()
                .HasForeignKey("ListId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("TaskManager.Models.TodoList", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("DeviceId")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("device_id");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("name");

            b.HasKey("Id");

            b.HasIndex("DeviceId");

            b.ToTable("lists", (string)null);
        });
#pragma warning restore 612, 618
    }
}
